channels:
  - usgs-astrogeology
  - conda-forge
  - defaults

dependencies:
  - boost >=1.78.0,<1.79
  - boost-cpp >=1.78.0,<1.79
  - cmake >=3.27,<3.28
  - cspice =67
  - eigen >=3, <4
  - isis
  - libgdal >=3.7,<3.8
  - libopencv >=4.7,<4.8
  - make
  - ninja >=1.7.2,<1.8
  - opencv >=4.7,<4.8
  - python >=3.10
  - python_abi >=3.10
  - pytest
  - qt-main>=5.15.8, <5.16
  - qwt <6.3.0
